language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.3
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
    - python: "3.3"
      env: DJANGO=1.3
    - python: "3.3"
      env: DJANGO=1.4
    - python: "3.4"
      env: DJANGO=1.3
    - python: "3.4"
      env: DJANGO=1.4
install:
  - pip install --timeout=30 -q Django==$DJANGO
  - pip install --timeout=30 pep8
  - pip install --timeout=30 pyflakes
  - pip install --timeout=30 -q -e .
before_script:
  - make verify
script:
  - make test
notifications:
  slack: smartfile:tbDIPzVJIPBpSz29kQw6b8RQ
